### PR TITLE
[WIP] Add missing Apache License headers

### PR DESCRIPTION
**Pull request by lresende**
Per license recommendation:

To apply the Apache License to your work, attach the license
boilerplate notice, The text should be enclosed in the appropriate
comment syntax for the file format. We also recommend that a file or
class name and description of purpose be included on the same
"printed page" as the copyright notice for easier identification
within third-party archives.

### CODE REVIEW

**Comment by lresende** [comment]
This is a work in progress, please do not merge it yet.
I want to do a second pass review, and also see if I can properly add the headers to yml files.

**Comment by animeshsingh** [comment]
@lresende Thanks - but lets hold on to this. We are not adding headers to every files in all the repos in github.com/IBM having Apache 2.0 license. As and when we move this in a more formal space in a foundation or so, we will revisit this.

**Comment by lresende** [comment]
@animeshsingh  FYI, this is a requirement of the Apache License. As an example, Apache releases would fail if they try to release without AL2 Headers except for files that don't accept comments. Having said that, I am definitely not volunteering to review/update every project on the IBM organization, but I feel encouraged to do so on the ones CODAIT is involved.

**Comment by animeshsingh** [comment]
Its a practice- not necessary.
http://www.apache.org/dev/apply-license.html#copy-per-file

As I mentioned, when we revisit this in a more formal space with a foundation and release et all, we can revisit these. We have lots of changes going back and forth currently, so best to come back to this.

**Comment by lresende** [comment]
> Its a practice- not necessary.
http://www.apache.org/dev/apply-license.html#copy-per-file

That's not my understanding. The direct link you posted above talks about having the full license details, which is enough to have only one (LICENSE file in the root of the repository in our case). But if you follow the [policy link] (http://www.apache.org/legal/src-headers.html) on that, you will see [this](http://www.apache.org/legal/src-headers.html#faq-siteindocs) and [this](http://www.apache.org/legal/src-headers.html#faq-exceptions). The actual [Apache License](https://www.apache.org/licenses/LICENSE-2.0#apply) describe these requirements as well.

**Comment by animeshsingh** [comment]
So that page states at the bottom that`s a requirement for projects inside ASF. Outside of that, it`s a recommended practice and author`s discretion.

Having said that, we are expecting a bunch of changes rolling out soon - lets include them as well and as Waldemar requested, if you have  script which generates these, we can merge it as part of this merge as well.

**Comment by lresende** [comment]
I will keep maintaining this and we can re-evaluate it after the new changes are available.

**Comment by fplk** [comment]
Might be obsolete. We pushed copyright headers as part of our pull routine.

**Comment by sboagibm** [comment]
@lresende can you rebase so we can merge?

**Comment by fplk** [comment]
Random checks revealed that the headers should be already applied in the recent code. We also now have two new pulls on top of the master here, so the code bases are severely out of sync. I'll thus close it. Please let us know if we should have missed the headers anywhere and thank you for the work on this.

**Comment by lresende** [comment]
@fplk After rebasing and running the license check again, there are still 214 files without a license header, and most of them are actual issues. I will get an updated pr in the next day or so, please reopen this pr.

```
Files with unapproved licenses:

  ./.gitattributes
  ./.gitignore
  ./.helmignore
  ./.travis.yml
  ./Chart.yaml
  ./README-cn.md
  ./env.txt
  ./gitupdate.sh
  ./glide.lock
  ./glide.yaml
  ./license-issues.txt
  ./rat.log
  ./values.yaml
  ./bin/addnew_march_15_2018.sh
  ./bin/create_static_pv.sh
  ./bin/create_static_volumes.sh
  ./bin/create_static_volumes_config.sh
  ./bin/dind-port-forward.sh
  ./bin/escape_for_sed.sh
  ./bin/kubecontext.sh
  ./bin/s3_driver.sh
  ./bin/dind_scripts/Dockerfile.compile
  ./bin/dind_scripts/build_ffdl.sh
  ./bin/dind_scripts/compile_s3fs.sh
  ./bin/dind_scripts/create_user.sh
  ./bin/dind_scripts/experimental_master.sh
  ./bin/dind_scripts/import_registry_certificates.sh
  ./bin/dind_scripts/install_docker.sh
  ./bin/dind_scripts/install_go.sh
  ./bin/dind_scripts/install_kubernetes.sh
  ./bin/dind_scripts/install_nfs.sh
  ./bin/dind_scripts/install_registry.sh
  ./bin/dind_scripts/launch_kubernetes.sh
  ./bin/dind_scripts/launch_registry.sh
  ./bin/dind_scripts/s3_driver.sh
  ./bin/ibmc_scripts/experimental_master.sh
  ./bin/test-pods/nfs-pv.yaml
  ./bin/test-pods/nfs-test-pod.yaml
  ./commons/certs/copy.sh
  ./commons/certs/generate.sh
  ./commons/certs/install.sh
  ./commons/framework/framework.go
  ./commons/mock_service/lcm.go
  ./commons/service/lcm.pb.go
  ./community/collaborators.yaml
  ./community/FfDL-H2Oai/README.md
  ./community/FfDL-H2Oai/h2o-model/Dockerfile.h2o3
  ./community/FfDL-H2Oai/h2o-model/h2o3-cluster.sh
  ./community/FfDL-H2Oai/h2o-model/manifest-h2o.yml
  ./community/FfDL-Seldon/README.md
  ./community/FfDL-Seldon/pytorch-model/README.md
  ./community/FfDL-Seldon/pytorch-model/bucket-secret.yaml
  ./community/FfDL-Seldon/pytorch-model/ffdl-mnist-deployment.json
  ./community/FfDL-Seldon/pytorch-model/requirements.txt
  ./community/FfDL-Seldon/pytorch-model/serving_ambassador.ipynb
  ./community/FfDL-Seldon/pytorch-model/serving_oauth.ipynb
  ./community/FfDL-Seldon/tf-model/README.md
  ./community/FfDL-Seldon/tf-model/bucket-secret.yaml
  ./community/FfDL-Seldon/tf-model/ffdl-mnist-deployment.json
  ./community/FfDL-Seldon/tf-model/requirements.txt
  ./community/FfDL-Seldon/tf-model/serving_ambassador.ipynb
  ./community/FfDL-Seldon/tf-model/serving_oauth.ipynb
  ./dashboard/.angular-cli.json
  ./dashboard/.gitignore
  ./dashboard/package-lock.json
  ./dashboard/package.json
  ./dashboard/tsconfig.json
  ./dashboard/tslint.json
  ./dashboard/e2e/tsconfig.e2e.json
  ./dashboard/src/tsconfig.app.json
  ./dashboard/src/tsconfig.spec.json
  ./dashboard/src/assets/.gitkeep
  ./dashboard/src/assets/font-awesome/HELP-US-OUT.txt
  ./dashboard/src/assets/font-awesome/css/font-awesome.min.css
  ./dashboard/src/assets/font-awesome/fonts/fontawesome-webfont.svg
  ./dashboard/src/assets/img/loading.svg
  ./demos/README.md
  ./demos/fashion-mnist-adversarial/.gitignore
  ./demos/fashion-mnist-adversarial/ART_with_FfDL.ipynb
  ./demos/fashion-mnist-adversarial/README.md
  ./demos/fashion-mnist-adversarial/requirements.txt
  ./demos/fashion-mnist-training/README.md
  ./demos/fashion-mnist-training/demo.md
  ./demos/fashion-mnist-training/fashion-mnist-webapp/.travis.yml
  ./demos/fashion-mnist-training/fashion-mnist-webapp/README.md
  ./demos/fashion-mnist-training/fashion-mnist-webapp/fashion-mnist-webapp.yaml
  ./demos/fashion-mnist-training/fashion-mnist-webapp/requirements.txt
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/css/bootstrap.min.css
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/css/featherlight.min.css
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/css/image-picker.css
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/fonts/glyphicons-halflings-regular.svg
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/js/d3.layout.cloud.js
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/js/d3.min.js
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/js/featherlight.min.js
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/js/image-picker.min.js
  ./demos/fashion-mnist-training/fashion-mnist-webapp/static/js/jquery-3.3.1.min.js
  ./demos/fashion-mnist-training/fashion-train/README.md
  ./demos/fashion-mnist-training/fashion-train/manifest-cpu.yml
  ./demos/fashion-mnist-training/fashion-train/manifest.yml
  ./demos/fashion-mnist-training/fashion-train/fashion-training/experiment.py
  ./demos/fashion-mnist-training/seldon-deployment/MyModel.py
  ./demos/fashion-mnist-training/seldon-deployment/README.md
  ./demos/fashion-mnist-training/seldon-deployment/bucket-secret.yaml
  ./demos/fashion-mnist-training/seldon-deployment/fashion-seldon.json
  ./demos/fashion-mnist-training/seldon-deployment/requirements.txt
  ./design/design_docs.md
  ./docs/troubleshooting.md
  ./etc/dashboards.json
  ./etc/converter/requirement.txt
  ./etc/converter/sample-FfDL.yaml
  ./etc/converter/sample-WML.yaml
  ./etc/dlaas-service-base/build/grpc-health-checker/.gitignore
  ./etc/dlaas-service-base/build/grpc-health-checker/glide.lock
  ./etc/dlaas-service-base/build/grpc-health-checker/glide.yaml
  ./etc/examples/README.md
  ./etc/examples/caffe-model/gpu-manifest.yml
  ./etc/examples/caffe-model/lenet_solver.prototxt
  ./etc/examples/caffe-model/lenet_train_test.prototxt
  ./etc/examples/caffe-model/manifest.yml
  ./etc/examples/caffe2-model/manifest.yml
  ./etc/examples/horovod/README.md
  ./etc/examples/horovod/manifest_pytorchmnist.yml
  ./etc/examples/horovod/manifest_tfmnist.yml
  ./etc/examples/horovod/tensorflow_mnist.py
  ./etc/examples/keras-test/manifest-py3.yml
  ./etc/examples/keras-test/mnist_cnn.py
  ./etc/examples/pytorch-model/manifest.yml
  ./etc/examples/tf-distributed/README.md
  ./etc/examples/tf-distributed/launcher.py
  ./etc/examples/tf-distributed/manifest.yml
  ./etc/examples/tf-distributed/mnist_dist_savemodel.py
  ./etc/examples/tf-model/convolutional_network.py
  ./etc/examples/tf-model/gpu-manifest.yml
  ./etc/examples/tf-model/input_data.py
  ./etc/examples/tf-model/manifest-for-test.yml
  ./etc/examples/tf-model/manifest-hostmount.yml
  ./etc/examples/tf-model/manifest.yml
  ./etc/examples/tf-summary-model/gpu-manifest.yml
  ./etc/examples/tf-summary-model/input_data.py
  ./etc/examples/tf-summary-model/manifest.yml
  ./etc/examples/tf-summary-model/runtb.sh
  ./etc/notebooks/art/.gitignore
  ./etc/notebooks/art/ART_model_robustness_check.ipynb
  ./etc/notebooks/art/README.md
  ./etc/notebooks/art/requirements.txt
  ./lcm/service/lcm/learner/container.go
  ./lcm/service/lcm/learner/image.go
  ./lcm/service/lcm/learner/image_test.go
  ./lcm/service/lcm/learner/imagesecrets.go
  ./lcm/service/lcm/learner/learner.go
  ./metrics/log_collectors/__init__.py
  ./metrics/log_collectors/emetrics_file/__init__.py
  ./metrics/log_collectors/emetrics_file/src/__init__.py
  ./metrics/log_collectors/regex_extractor/__init__.py
  ./metrics/log_collectors/regex_extractor/src/__init__.py
  ./metrics/log_collectors/regex_extractor/src/patterns/common-patterns
  ./metrics/log_collectors/simple_log_collector/__init__.py
  ./metrics/log_collectors/simple_log_collector/src/__init__.py
  ./metrics/log_collectors/tensorboard/__init__.py
  ./metrics/log_collectors/tensorboard/src/__init__.py
  ./metrics/log_collectors/tensorboard/src/run.sh
  ./metrics/log_collectors/training_data_service_client/__init__.py
  ./metrics/log_collectors/training_data_service_client/training_data_pb2.py
  ./metrics/log_collectors/training_data_service_client/training_data_pb2_grpc.py
  ./metrics/service/grpc_training_data_v1/training_data.pb.go
  ./metrics/service/grpc_training_data_v1/training_data.swagger.json
  ./metrics/service/grpc_training_data_v1/training_data.swagger.yml
  ./metrics/service/grpc_training_data_v1/python/training_data_pb2.py
  ./metrics/service/grpc_training_data_v1/python/training_data_pb2_grpc.py
  ./persistentvol/task-pv-claim.yaml
  ./persistentvol/task-pv-pod.yaml
  ./persistentvol/task-pv-volume.yaml
  ./restapi/api_v1/server/doc.go
  ./restapi/api_v1/server/server.go
  ./restapi/middleware/response_writer.go
  ./samples/models.md
  ./storage-plugin/Chart.yaml
  ./storage-plugin/values.yaml
  ./storage-plugin/templates/deployer.yaml
  ./storage-plugin/templates/ibmc-s3fs-standard-StorageClass.yaml
  ./storage-plugin/templates/provisioner-sa.yaml
  ./storage-plugin/templates/provisioner.yaml
  ./storage-plugin/templates/volume.yaml
  ./templates/infrastructure/etcd.yml
  ./templates/infrastructure/mongo.yml
  ./templates/infrastructure/storage.yml
  ./templates/monitoring/alertmanager-configmap.yml
  ./templates/monitoring/alertmanager-deployment.yml
  ./templates/monitoring/alertmanager-service.yml
  ./templates/monitoring/alertrules-configmap.yml
  ./templates/monitoring/prometheus-configmap.yml
  ./templates/monitoring/prometheus-deployment.yml
  ./templates/monitoring/prometheus-service.yml
  ./templates/monitoring/pushgateway-configmap.yml
  ./templates/monitoring/pushgateway-deployment.yml
  ./templates/monitoring/pushgateway-service.yml
  ./templates/services/lcm-deployment.yml
  ./templates/services/lcm-rbac.yml
  ./templates/services/lcm-secrets.yml
  ./templates/services/lcm-service.yml
  ./templates/services/learner-configmap.yml
  ./templates/services/learner-rsa-keys.yml
  ./templates/services/restapi-deployment.yml
  ./templates/services/restapi-service.yml
  ./templates/services/trainer-deployment.yml
  ./templates/services/trainer-secrets.yml
  ./templates/services/trainer-service.yml
  ./templates/services/trainingdata-deployment.yml
  ./templates/services/trainingdata-secrets.yml
  ./templates/services/trainingdata-service.yml
  ./templates/services/web-ui.yml
  ./trainer/glide.yaml
  ./trainer/instrumentation/call_logger.go
  ./trainer/trainer/grpc_trainer_v2/trainer.pb.go
```

**Pull request closed without merging**
